<?php
return array (
  'cfg_basehost' => 'http://www.maojian.com',
  'cfg_indexurl' => '/',
  'cfg_indexname' => '官网主页',
  'cfg_webname' => '我的主页',
  'cfg_powerby' => 'Copyright © 2008 - 2012 EaglePHP. All Rights Reserved',
  'cfg_keywords' => 'EaglePHP Framework',
  'cfg_description' => 'EaglePHP，是一款开源、高效、面向对象的PHP MVC开发框架，完全基于PHP5可用于开发WEB程序和服务，借鉴国外优秀框架的设计思路，分层的设计思想使独立开发成为可能，建立模型推动代码的重用，有助于促进快速软件开发(RAD)和创建更稳定的程序，节约了开发者的时间，并减少重复编写代码的劳动。',
  'cfg_beian' => '',
  'cfg_cmspath' => '/EaglePHP',
  'cfg_cookie_encode' => 'dfergfddf454seddd',
  'cfg_backup_dir' => 'Backup',
  'cfg_adminemail' => 'maojianlw@139.com',
  'cfg_domain_cookie' => '/',
  'cfg_eag_log' => '0',
  'cfg_ftp_host' => 'localhost',
  'cfg_ftp_port' => '21',
  'cfg_ftp_user' => 'maojian',
  'cfg_ftp_pwd' => '123456',
  'cfg_ftp_root' => '/',
  'cfg_ftp_mkdir' => '1',
  'cfg_sendmail_bysmtp' => '1',
  'cfg_smtp_server' => 'smtp.163.com',
  'cfg_smtp_port' => '25',
  'cfg_smtp_usermail' => 'china.boy.mj@163.com',
  'cfg_smtp_user' => 'maojian',
  'cfg_smtp_password' => 'maojian',
  'cfg_admin_sysname' => 'EaglePHP Framework',
  'cfg_admin_sysdesc' => 'EaglePHP，是一款开源、高效、面向对象的PHP MVC开发框架，完全基于PHP5可用于开发WEB程序和服务，借鉴国外优秀框架的设计思路，分层的设计思想使独立开发成为可能，建立模型推动代码的重用，有助于促进快速软件开发(RAD)和创建更稳定的程序，节约了开发者的时间，并减少重复编写代码的劳动。',
  'cfg_sys_version' => 'v 2.2',
  'cfg_access_log' => '0',
  'cfg_system_log' => '1',
  'cfg_debug_mode' => '1',
  'cfg_mysql_type' => 'mysql',
  'cfg_orm_dir' => 'Field',
  'cfg_session_dir' => 'Session',
  'cfg_img_width' => '100',
  'cfg_img_height' => '100',
  'cfg_original_imgdir' => 'photo/original/',
  'cfg_middle_imgdir' => 'photo/middle/',
  'cfg_thumbnail_imgdir' => 'photo/thumbnail/',
  'cfg_memcache_host' => '127.0.0.1',
  'cfg_memcache_port' => '11211',
  'cfg_auot_description' => '100',
  'cfg_rm_remote' => '0',
  'cfg_arc_dellink' => '1',
  'cfg_arc_autopic' => '0',
  'cfg_arc_autokeyword' => '1',
  'cfg_title_maxlen' => '60',
  'cfg_check_title' => '1',
  'cfg_upload_switch' => '1',
  'cfg_html_dir' => '/a',
  'cfg_html_make' => '0',
  'cfg_adv_dir' => 'adv/',
  'cfg_filter_word' => '非典|艾滋病|阳痿|她妈|它妈|他妈|你妈|去死|贱人',
  'cfg_cache_dir' => 'File',
  'cfg_cache_type' => 'File',
  'cfg_cache_time' => '0',
  'cfg_login_email' => '0',
  'cfg_debug_email' => '0',
  'cfg_case_dir' => 'case/',
  'cfg_video_dir' => 'video/',
  'cfg_taobao_isopen' => '1',
  'cfg_taobao_appkey' => '21072832',
  'cfg_taobao_secret' => '6885676831c4b9837090c03b26c85819',
  'cfg_taobao_callback' => '',
  'cfg_taobao_pid' => '32251410',
  'cfg_refresh_time' => '0',
  'cfg_redis_host' => '127.0.0.1',
  'cfg_redis_port' => '6379',
  'cfg_ping_sites' => 'http://ping.baidu.com/ping/RPC2http://blogsearch.google.com/ping/RPC2http://blog.youdao.com/ping/RPC2http://rpc.pingomatic.com/http://www.feedsky.com/api/RPC2http://xianguo.com/xmlrpc/ping.phphttp://www.bloglines.com/ping',
  'cfg_open_rewrite' => '0',
  'cfg_links_dir' => 'links/',
  'cfg_open_weather' => '1',
);
?>